---
# tasks file for docker

- include: Debian.yml
  when: ansible_os_family == "Debian"

- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: add user to group
  user: name={{ user }} append=yes groups=docker
  when: user
